{
    'name': 'Sistem Manajemen Inventaris',
    'version': '17.0.1.0.0',
    'summary': 'Manajemen inventaris bahan baku CV Dunia Offset Printing',
    'author': 'K02-G06',
    'category': 'Inventory',
    'license': 'LGPL-3',
    'depends': ['base', 'mail', 'web', 'bus'],
    'data': [
        'security/smi_security.xml',
        'security/ir.model.access.csv',
        'data/demo_users.xml',
        'data/email_templates.xml',
        'data/seed_materials.xml',
        'views/auth_templates.xml',
        'views/layout_template.xml',
        'views/dashboard_views.xml',
        'views/stock_list_template.xml',
        'views/stock_form_template.xml',
        'views/stock_detail_template.xml',
        'views/denah_template.xml',
        'views/material_views.xml',
        'views/stock_views.xml',
        'views/menu_views.xml',
        'views/order_views.xml',
        'views/order_list_template.xml',
        'views/order_form_step1_template.xml',
        'views/order_form_step2_template.xml',
        'views/order_form_step3_template.xml',
        'views/order_detail_template.xml',
        'views/activity_template.xml',
        'views/pengguna_template.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'inventory_smi/static/src/css/smi_theme.css',
            'inventory_smi/static/src/js/components/MapWidget.js',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
}
